GET http://localhost:3000/users/

###

GET http://localhost:3000/users/6155386540422d1ebd6c5f15

###

POST http://localhost:3000/users/
Content-Type: application/json

{
    "email": "john.doe@cloud.com",
    "name": "John Doe Cloud",
    "password": "12345"
}

### 

PATCH http://localhost:3000/users/6155386540422d1ebd6c5f15
Content-Type: application/json

{
  "email": "john2.doe2@user.com",
  "name": "John2 Doe3",
  "passowrd": "qwert"
}

###

DELETE http://localhost:3000/users/6155382540422d1ebd6c5f12
