version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    entrypoint: ./.docker/app/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=devontherun
      - ME_CONFIG_BASICAUTH_PASSWORD=123mudar
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123mudar
    depends_on:
      - db

  db:
    image: mongo:4.0.24
    environment:
      - MONGO_INITDB_DATABASE=totalzero
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123mudar
      - MONGO_APPLICATION_DATABASE=totalzero
      - MONGO_APPLICATION_USERNAME=dotr
      - MONGO_APPLICATION_PASSWORD=123mudar
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo/db:/data/db
      - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
